# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fetch_forecast_data_all": "00_core.ipynb",
         "project_id": "00_core.ipynb",
         "city_lat": "00_core.ipynb",
         "city_lon": "00_core.ipynb",
         "start_date": "00_core.ipynb",
         "end_date": "00_core.ipynb",
         "fetch_forecast_data_lead": "00_core.ipynb",
         "fetch_forecast_data_lead2": "00_core.ipynb",
         "evaluate_campaign_trigger": "00_core.ipynb",
         "assign_ad_type": "00_core.ipynb",
         "get_campaign_hist": "00_core.ipynb",
         "campaign_heatmap": "00_core.ipynb",
         "create_map": "00_core.ipynb",
         "map_campaigns_by_day": "00_core.ipynb",
         "data": "00_core.ipynb",
         "get_campaign_summary": "00_core.ipynb",
         "get_state_capitals": "01_utils.ipynb",
         "get_lat_lon": "01_utils.ipynb",
         "create_geo_query_list": "01_utils.ipynb",
         "round_to_grid": "01_utils.ipynb",
         "get_local_peak_hours": "01_utils.ipynb",
         "lat_lons": "01_utils.ipynb",
         "peak_hours": "01_utils.ipynb",
         "get_timezone_offset": "01_utils.ipynb",
         "offset_hours": "01_utils.ipynb",
         "calculate_search_radius": "01_utils.ipynb"}

modules = ["core.py",
           "utils.py"]

doc_url = "https://victorymr.github.io/forecast_action/"

git_url = "https://github.com/victorymr/forecast_action/tree/main/"

def custom_doc_links(name): return None
